# Data Science Project Components

**Learning objectives:**

-   Compare and contrast the tiers of the three-tier app architecture vs the seven data science services.
-   Answer the two data-storage questions about an app: storage format and storage location.
-   Choose the appropriate storage solution for an app.
-   Authorize an app to access data.
-   Consider database-as-a-servie options.

## SLIDE 1

- ADD SLIDES AS SECTIONS (`##`).
- TRY TO KEEP THEM RELATIVELY SLIDE-LIKE; THESE ARE NOTES, NOT THE BOOK ITSELF.

## Review

+---------------------------------------+--------------------------------------+
| Learning Objective                    | What Did We Learn?                   |
+=======================================+======================================+
| TEXT OF LO IN HERE                    | IF YOU CAN FIND A LESS PAINFUL WAY TO|
|                                       | DO THIS, DO SO!                      |
+---------------------------------------+--------------------------------------+
| TEXT OF LO IN HERE                    | IF YOU CAN FIND A LESS PAINFUL WAY TO|
|                                       | DO THIS, DO SO!                      |
+---------------------------------------+--------------------------------------+
| TEXT OF LO IN HERE                    | IF YOU CAN FIND A LESS PAINFUL WAY TO|
|                                       | DO THIS, DO SO!                      |
+---------------------------------------+--------------------------------------+

## Meeting Videos

### Cohort 1

`r knitr::include_url("https://www.youtube.com/embed/URL")`

<details>
<summary> Meeting chat log </summary>

```
LOG
```
</details>
