project:
  type: website
  pre-render: generate_chapters.R
  render:
  - slides/*
  - videos/*
  - '*.qmd'
format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: false
    link-external-newwindow: true
execute:
  freeze: auto
website:
  title: DevOps for Data Science Book Club
  sidebar:
    style: docked
    search: true
    tools:
    - icon: github
      href: https://github.com/r4ds/bookclub-do4ds
    - icon: youtube
      href: https://dslc.video/do4ds
    - icon: mastodon
      href: https://fosstodon.org/@DSLC
    - icon: linkedin
      href: https://www.linkedin.com/company/dslc-io
    contents:
    - index.qmd
    - file: slides/00.qmd
      target: advr_club-slides
    - section: DevOps Lessons for Data Science
      contents:
      - 01.qmd
      - 02.qmd
      - 03.qmd
      - 04.qmd
      - 05.qmd
      - 06.qmd
    - section: IT/Admin for Data Science
      contents:
      - 07.qmd
      - 08.qmd
      - 09.qmd
      - 11.qmd
      - 12.qmd
      - 13.qmd
      - 14.qmd
    - section: Enterprise-Grade Data Science
      contents:
      - 15.qmd
      - 16.qmd
      - 17.qmd
      - 18.qmd
