--- 
title: "DevOps for Data Science Book Club"
author: "The R4DS Online Learning Community"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
github-repo: r4ds/bookclub-do4ds
description: "This is the product of the R4DS Online Learning Community's DevOps for Data Science Book Club."
---

# Welcome {-}

Welcome to the bookclub! 

This is a companion for the book [_DevOps for Data Science_](https://do4ds.com/) by Alex K Gold (copyright 2022).
This companion is available at [r4ds.io/do4ds](https://r4ds.io/do4ds).

This website is being developed by the [R4DS Online Learning Community](https://rfordatasci.com). Follow along, and [join the community](https://r4ds.io/join) to participate.

This companion follows the [R4DS Online Learning Community Code of Conduct](https://r4ds.io/conduct).

## Book club meetings {-}

-   Each week, a volunteer will present a chapter from the book (or part of a chapter).
    -   **This is the best way to learn the material.**
-   Presentations will usually consist of a review of the material, a discussion, and/or a demonstration of the principles presented in that chapter.
-   More information about how to present is available in the [github repo](https://github.com/r4ds/bookclub-do4ds).
-   Presentations will be recorded, and will be available on the [R4DS Online Learning Community YouTube Channel](https://r4ds.io/youtube).
-   "None of us is as smart as all of us." ([source](https://www.marketplace.org/shows/make-me-smart/))
    -   Don't be afraid to ask questions!

## Pace {-}

-   We'll *try* to cover 1 chapter/week, but...
-   ...It's ok to split chapters when they feel like too much.
-   We will try to meet every week, but will likely take some breaks for holidays, etc.

## Learning objectives {-}

-   I am a big fan!
    -   Students who read with LOs in mind **retain more.**
-   **Tips:**
    -   "When you finish reading this Chapter, you will be able to..."
    -   *Very* roughly **1 per section.**
-   I'll ***try*** to have them in the repo by Tuesday each week.


# Introduction {-}

**Learning objectives:**

-   Recognize the **history of DevOps.**
-   Differentiate between **DevOps** (knowledge, practices, and tools) and **IT/Admins** (people and roles).
-   Recognize **red flags about IT/Admin functions** and what they might indicate.
-   Organize the content that will be **covered in this book.**

## Devops? {-}

-   Grew out of **Agile software development (2001).**
    -   Deliver small units, collect feedback, iterate.
-   Needed similar process to **get the iterations deployed.**
-   **DevOps (~2010)** is the **system/discipline.**

## DevOps vs IT/Admins {-}

-   **DevOps** 
    -   Knowledge, practices, & tools
    -   Put things into prod
    -   Safely & easily
-   **IT/Admins**
    -   People/roles who manage the servers, etc.
    -   Many names:
        -   Information Technology (IT)
        -   SysAdmin
        -   Site Reliability Engineering (SRE)
        -   DevOps
        -   Subdivisions (see next slide)

## Red Flags about IT/Admins {-}

1. **Subdivided** (security, databases, networking, etc)
    -   **Pros:** Super-deep expertise.
    -   **Cons:** Hard to find the right person.
2. **Outsourced**
    -   **Pros:** Companies can get competence fast.
    -   **Cons:** Scheduling, often high turnover.
3. **Nobody**
    -   **Pros:** Freedom!
    -   **Cons:** It's all up to you!

## This Book {-}

-   **Section 1:** Patterns & principles to grease the path to production.
-   **Section 2:** Vocab & beginnings of DIY.
-   **Section 3:** Hands-on DIY. Still very very in progress.

## DevOps Lessons for Data Science {-}

**Learning objectives:**

-   Describe the **core principles of DevOps.**
-   Apply **DevOps best practices** to **data science.**


## The 5 Tenets of DevOps {-}

1.  Code should be **well-tested** and tests should be **automated.**
2.  **Updates** should be **frequent** and **low-risk.**
3.  **Security** concerns should be considered **up front as part of architecture.**
4.  **Production** systems should have **monitoring and logging.**
5.  Frequent opportunities for **review, change, and updating** should be **built into the system** -- both **culturally** and **technically.**

## DevOps for Data Science {-}

-   **Use CI/CD ➡️ Code Promotion and Integration Processes**
    -   Structure output so moving to prod or updating is easy.
-   **Infrastructure as Code ➡️ Manage Environments as Code**
    -   Reproducible & secure environments are... reproducible and secure!
-   **Microservices ➡️ Data Science Project Components**
    -   Figure out how to subdivide things to make updating less painful.
-   **Monitoring & Logging ➡️ Monitoring & Logging**
    -   Data science doesn't do enough of this, but he'll tell us how we should!
-   **Other Things ➡️ Other Things 🙃**
    -   Chapter about Docker for Data Science here, because it deserves its own chapter.
    -   Section 2 will be all about things like communication, collaboration, and review practices.

## Meeting Videos {-}

### Cohort 1 {-}

`r knitr::include_url("https://www.youtube.com/embed/3-pFRbbaGpg")`
